// Country ISO codes mapping for API requests
// Provides mapping between country names and their ISO 3166-1 alpha-2 and alpha-3 codes
// Used for fetching data from World Bank, IMF, OECD and other official data sources

// Map country names to their ISO codes
export const countryCodesMap: Record<string, { alpha2: string, alpha3: string }> = {
  "Afghanistan": { alpha2: "AF", alpha3: "AFG" },
  "Albania": { alpha2: "AL", alpha3: "ALB" },
  "Algeria": { alpha2: "DZ", alpha3: "DZA" },
  "Angola": { alpha2: "AO", alpha3: "AGO" },
  "Argentina": { alpha2: "AR", alpha3: "ARG" },
  "Armenia": { alpha2: "AM", alpha3: "ARM" },
  "Australia": { alpha2: "AU", alpha3: "AUS" },
  "Austria": { alpha2: "AT", alpha3: "AUT" },
  "Azerbaijan": { alpha2: "AZ", alpha3: "AZE" },
  "Bahrain": { alpha2: "BH", alpha3: "BHR" },
  "Bangladesh": { alpha2: "BD", alpha3: "BGD" },
  "Belarus": { alpha2: "BY", alpha3: "BLR" },
  "Belgium": { alpha2: "BE", alpha3: "BEL" },
  "Bolivia": { alpha2: "BO", alpha3: "BOL" },
  "Bosnia and Herzegovina": { alpha2: "BA", alpha3: "BIH" },
  "Botswana": { alpha2: "BW", alpha3: "BWA" },
  "Brazil": { alpha2: "BR", alpha3: "BRA" },
  "Brunei": { alpha2: "BN", alpha3: "BRN" },
  "Bulgaria": { alpha2: "BG", alpha3: "BGR" },
  "Cambodia": { alpha2: "KH", alpha3: "KHM" },
  "Cameroon": { alpha2: "CM", alpha3: "CMR" },
  "Canada": { alpha2: "CA", alpha3: "CAN" },
  "Chad": { alpha2: "TD", alpha3: "TCD" },
  "Chile": { alpha2: "CL", alpha3: "CHL" },
  "China": { alpha2: "CN", alpha3: "CHN" },
  "Colombia": { alpha2: "CO", alpha3: "COL" },
  "Croatia": { alpha2: "HR", alpha3: "HRV" },
  "Cuba": { alpha2: "CU", alpha3: "CUB" },
  "Cyprus": { alpha2: "CY", alpha3: "CYP" },
  "Czech Republic": { alpha2: "CZ", alpha3: "CZE" },
  "Democratic Republic of the Congo": { alpha2: "CD", alpha3: "COD" },
  "Denmark": { alpha2: "DK", alpha3: "DNK" },
  "Dominican Republic": { alpha2: "DO", alpha3: "DOM" },
  "Ecuador": { alpha2: "EC", alpha3: "ECU" },
  "Egypt": { alpha2: "EG", alpha3: "EGY" },
  "Estonia": { alpha2: "EE", alpha3: "EST" },
  "Ethiopia": { alpha2: "ET", alpha3: "ETH" },
  "Finland": { alpha2: "FI", alpha3: "FIN" },
  "France": { alpha2: "FR", alpha3: "FRA" },
  "Georgia": { alpha2: "GE", alpha3: "GEO" },
  "Germany": { alpha2: "DE", alpha3: "DEU" },
  "Ghana": { alpha2: "GH", alpha3: "GHA" },
  "Greece": { alpha2: "GR", alpha3: "GRC" },
  "Greenland": { alpha2: "GL", alpha3: "GRL" },
  "Guatemala": { alpha2: "GT", alpha3: "GTM" },
  "Honduras": { alpha2: "HN", alpha3: "HND" },
  "Hungary": { alpha2: "HU", alpha3: "HUN" },
  "Iceland": { alpha2: "IS", alpha3: "ISL" },
  "India": { alpha2: "IN", alpha3: "IND" },
  "Indonesia": { alpha2: "ID", alpha3: "IDN" },
  "Iran": { alpha2: "IR", alpha3: "IRN" },
  "Iraq": { alpha2: "IQ", alpha3: "IRQ" },
  "Ireland": { alpha2: "IE", alpha3: "IRL" },
  "Israel": { alpha2: "IL", alpha3: "ISR" },
  "Italy": { alpha2: "IT", alpha3: "ITA" },
  "Ivory Coast": { alpha2: "CI", alpha3: "CIV" },
  "Jamaica": { alpha2: "JM", alpha3: "JAM" },
  "Japan": { alpha2: "JP", alpha3: "JPN" },
  "Jordan": { alpha2: "JO", alpha3: "JOR" },
  "Kazakhstan": { alpha2: "KZ", alpha3: "KAZ" },
  "Kenya": { alpha2: "KE", alpha3: "KEN" },
  "Kuwait": { alpha2: "KW", alpha3: "KWT" },
  "Kyrgyzstan": { alpha2: "KG", alpha3: "KGZ" },
  "Laos": { alpha2: "LA", alpha3: "LAO" },
  "Latvia": { alpha2: "LV", alpha3: "LVA" },
  "Lebanon": { alpha2: "LB", alpha3: "LBN" },
  "Libya": { alpha2: "LY", alpha3: "LBY" },
  "Lithuania": { alpha2: "LT", alpha3: "LTU" },
  "Luxembourg": { alpha2: "LU", alpha3: "LUX" },
  "Madagascar": { alpha2: "MG", alpha3: "MDG" },
  "Malaysia": { alpha2: "MY", alpha3: "MYS" },
  "Mali": { alpha2: "ML", alpha3: "MLI" },
  "Malta": { alpha2: "MT", alpha3: "MLT" },
  "Mexico": { alpha2: "MX", alpha3: "MEX" },
  "Moldova": { alpha2: "MD", alpha3: "MDA" },
  "Mongolia": { alpha2: "MN", alpha3: "MNG" },
  "Montenegro": { alpha2: "ME", alpha3: "MNE" },
  "Morocco": { alpha2: "MA", alpha3: "MAR" },
  "Mozambique": { alpha2: "MZ", alpha3: "MOZ" },
  "Myanmar": { alpha2: "MM", alpha3: "MMR" },
  "Namibia": { alpha2: "NA", alpha3: "NAM" },
  "Nepal": { alpha2: "NP", alpha3: "NPL" },
  "Netherlands": { alpha2: "NL", alpha3: "NLD" },
  "New Zealand": { alpha2: "NZ", alpha3: "NZL" },
  "Nicaragua": { alpha2: "NI", alpha3: "NIC" },
  "Niger": { alpha2: "NE", alpha3: "NER" },
  "Nigeria": { alpha2: "NG", alpha3: "NGA" },
  "North Korea": { alpha2: "KP", alpha3: "PRK" },
  "North Macedonia": { alpha2: "MK", alpha3: "MKD" },
  "Norway": { alpha2: "NO", alpha3: "NOR" },
  "Oman": { alpha2: "OM", alpha3: "OMN" },
  "Pakistan": { alpha2: "PK", alpha3: "PAK" },
  "Panama": { alpha2: "PA", alpha3: "PAN" },
  "Papua New Guinea": { alpha2: "PG", alpha3: "PNG" },
  "Paraguay": { alpha2: "PY", alpha3: "PRY" },
  "Peru": { alpha2: "PE", alpha3: "PER" },
  "Philippines": { alpha2: "PH", alpha3: "PHL" },
  "Poland": { alpha2: "PL", alpha3: "POL" },
  "Portugal": { alpha2: "PT", alpha3: "PRT" },
  "Qatar": { alpha2: "QA", alpha3: "QAT" },
  "Romania": { alpha2: "RO", alpha3: "ROU" },
  "Russia": { alpha2: "RU", alpha3: "RUS" },
  "Saudi Arabia": { alpha2: "SA", alpha3: "SAU" },
  "Senegal": { alpha2: "SN", alpha3: "SEN" },
  "Serbia": { alpha2: "RS", alpha3: "SRB" },
  "Singapore": { alpha2: "SG", alpha3: "SGP" },
  "Slovakia": { alpha2: "SK", alpha3: "SVK" },
  "Slovenia": { alpha2: "SI", alpha3: "SVN" },
  "Solomon Islands": { alpha2: "SB", alpha3: "SLB" },
  "Somalia": { alpha2: "SO", alpha3: "SOM" },
  "South Africa": { alpha2: "ZA", alpha3: "ZAF" },
  "South Korea": { alpha2: "KR", alpha3: "KOR" },
  "South Sudan": { alpha2: "SS", alpha3: "SSD" },
  "Spain": { alpha2: "ES", alpha3: "ESP" },
  "Sri Lanka": { alpha2: "LK", alpha3: "LKA" },
  "Sudan": { alpha2: "SD", alpha3: "SDN" },
  "Svalbard": { alpha2: "SJ", alpha3: "SJM" },
  "Sweden": { alpha2: "SE", alpha3: "SWE" },
  "Switzerland": { alpha2: "CH", alpha3: "CHE" },
  "Syria": { alpha2: "SY", alpha3: "SYR" },
  "Taiwan": { alpha2: "TW", alpha3: "TWN" },
  "Tajikistan": { alpha2: "TJ", alpha3: "TJK" },
  "Tanzania": { alpha2: "TZ", alpha3: "TZA" },
  "Thailand": { alpha2: "TH", alpha3: "THA" },
  "Tunisia": { alpha2: "TN", alpha3: "TUN" },
  "Turkey": { alpha2: "TR", alpha3: "TUR" },
  "Turkmenistan": { alpha2: "TM", alpha3: "TKM" },
  "Uganda": { alpha2: "UG", alpha3: "UGA" },
  "Ukraine": { alpha2: "UA", alpha3: "UKR" },
  "United Arab Emirates": { alpha2: "AE", alpha3: "ARE" },
  "United Kingdom": { alpha2: "GB", alpha3: "GBR" },
  "United States": { alpha2: "US", alpha3: "USA" },
  "Uruguay": { alpha2: "UY", alpha3: "URY" },
  "Uzbekistan": { alpha2: "UZ", alpha3: "UZB" },
  "Venezuela": { alpha2: "VE", alpha3: "VEN" },
  "Vietnam": { alpha2: "VN", alpha3: "VNM" },
  "Yemen": { alpha2: "YE", alpha3: "YEM" },
  "Zambia": { alpha2: "ZM", alpha3: "ZMB" },
  "Zimbabwe": { alpha2: "ZW", alpha3: "ZWE" }
};

// Utility function to get ISO codes for a country name
export function getCountryCodes(countryName: string): { alpha2: string, alpha3: string } | undefined {
  return countryCodesMap[countryName];
}

// Reverse lookup: get country name from ISO code
export function getCountryNameFromCode(code: string): string | undefined {
  // Check if it's an alpha-2 code
  const alpha2Match = Object.entries(countryCodesMap).find(
    ([, codes]) => codes.alpha2.toLowerCase() === code.toLowerCase()
  );
  
  if (alpha2Match) {
    return alpha2Match[0];
  }
  
  // Check if it's an alpha-3 code
  const alpha3Match = Object.entries(countryCodesMap).find(
    ([, codes]) => codes.alpha3.toLowerCase() === code.toLowerCase()
  );
  
  return alpha3Match ? alpha3Match[0] : undefined;
}