/**
 * server/engine — LLM-FREE computation engine.
 *
 * Every number produced here is COMPUTED in plain code from real data feeds
 * (Finnhub, World Bank, ExchangeRate) using deterministic formulas. No value in
 * this directory is generated by an LLM. This is enforced by tests/engine.test.ts
 * (the "One Rule": the engine imports no LLM client).
 *
 * These numbers are verifiable, reproducible, and auditable. They are NOT
 * predictions and make no accuracy guarantee — they report what the data gives.
 */

export * from "./portfolio";
export * from "./risk";
export * from "./macro";
export * from "./data-sources";
export * from "./historical-prices";

export const ENGINE_SOURCES = {
  finnhub: "Finnhub",
  alphaVantage: "Alpha Vantage",
  worldBank: "World Bank",
  exchangeRate: "ExchangeRate",
} as const;
