import { ReactNode } from "react";
import { Info, Scale, Sparkles, ShieldAlert, Database } from "lucide-react";
import { useTranslation } from "react-i18next";
import { cn } from "@/lib/utils";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

interface DisclaimerProps {
  className?: string;
  children?: ReactNode;
}

/**
 * FinancialDisclaimer — persistent "informational only / not financial advice"
 * notice. Render this ABOVE any financial/portfolio/investment guidance so the
 * user sees it before results.
 */
export function FinancialDisclaimer({ className, children }: DisclaimerProps) {
  const { t } = useTranslation();
  return (
    <div
      role="note"
      data-testid="disclaimer-financial"
      className={cn(
        "flex items-start gap-2.5 rounded-md border border-amber-300/70 bg-amber-50 px-3 py-2.5 text-amber-900",
        className,
      )}
    >
      <Info className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" aria-hidden />
      <p className="text-xs leading-relaxed">
        <span className="font-semibold">
          {t("disclaimer.financialTitle", "Informational only — not financial advice.")}
        </span>{" "}
        {children ??
          t(
            "disclaimer.financialBody",
            "WealthSync provides AI-generated insights for research and education. It is not a registered investment adviser. Verify figures independently and consult a qualified professional before making financial decisions.",
          )}
      </p>
    </div>
  );
}

/**
 * LegalDisclaimer — "not legal advice" notice for AI-drafted contracts and
 * regulatory guidance surfaces.
 */
export function LegalDisclaimer({ className, children }: DisclaimerProps) {
  const { t } = useTranslation();
  return (
    <div
      role="note"
      data-testid="disclaimer-legal"
      className={cn(
        "flex items-start gap-2.5 rounded-md border border-slate-300 bg-slate-50 px-3 py-2.5 text-slate-700",
        className,
      )}
    >
      <Scale className="mt-0.5 h-4 w-4 shrink-0 text-slate-500" aria-hidden />
      <p className="text-xs leading-relaxed">
        <span className="font-semibold">
          {t("disclaimer.legalTitle", "Not legal advice.")}
        </span>{" "}
        {children ??
          t(
            "disclaimer.legalBody",
            "AI-generated documents and guidance are drafts for convenience only. Review with a qualified attorney before signing or relying on them.",
          )}
      </p>
    </div>
  );
}

/**
 * AIEstimateBadge — provenance label for a number that is produced by the AI
 * model rather than computed from a verified data source. Be honest: an LLM
 * estimate is not a calculated metric.
 */
export function AIEstimateBadge({
  className,
  label,
  tooltip,
}: {
  className?: string;
  label?: string;
  tooltip?: string;
}) {
  const { t } = useTranslation();
  return (
    <TooltipProvider delayDuration={150}>
      <Tooltip>
        <TooltipTrigger asChild>
          <span
            data-testid="badge-ai-estimate"
            className={cn(
              "inline-flex cursor-help items-center gap-1 rounded-full border border-violet-200 bg-violet-50 px-1.5 py-0.5 text-[10px] font-medium leading-none text-violet-700",
              className,
            )}
          >
            <Sparkles className="h-2.5 w-2.5" aria-hidden />
            {label ?? t("provenance.aiEstimate", "AI estimate")}
          </span>
        </TooltipTrigger>
        <TooltipContent className="max-w-[220px] text-xs">
          {tooltip ??
            t(
              "provenance.aiEstimateTooltip",
              "Generated by the AI model from your inputs and context — not a figure calculated from verified market data. Treat as directional, not precise.",
            )}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

/**
 * ComputedBadge — provenance label for a number that IS derived from real data
 * (e.g. Finnhub, World Bank, or a deterministic calculation).
 */
export function ComputedBadge({
  className,
  label,
  tooltip,
}: {
  className?: string;
  label?: string;
  tooltip?: string;
}) {
  const { t } = useTranslation();
  return (
    <TooltipProvider delayDuration={150}>
      <Tooltip>
        <TooltipTrigger asChild>
          <span
            data-testid="badge-computed"
            className={cn(
              "inline-flex cursor-help items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-1.5 py-0.5 text-[10px] font-medium leading-none text-emerald-700",
              className,
            )}
          >
            <ShieldAlert className="h-2.5 w-2.5" aria-hidden />
            {label ?? t("provenance.computed", "Live data")}
          </span>
        </TooltipTrigger>
        <TooltipContent className="max-w-[220px] text-xs">
          {tooltip ??
            t(
              "provenance.computedTooltip",
              "Calculated from verified data sources (e.g. Finnhub, World Bank).",
            )}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

/**
 * SourceBadge — provenance label for a number that is FETCHED as-is from an
 * authoritative source (e.g. GDP, inflation, FX), NOT calculated by us. Reads
 * "Source: X" to make clear we are reporting an official figure verbatim, not
 * deriving it. Distinct from ComputedBadge (we did the math) and AIEstimateBadge
 * (the model guessed).
 */
export function SourceBadge({
  className,
  label,
  tooltip,
}: {
  className?: string;
  label?: string;
  tooltip?: string;
}) {
  const { t } = useTranslation();
  return (
    <TooltipProvider delayDuration={150}>
      <Tooltip>
        <TooltipTrigger asChild>
          <span
            data-testid="badge-source"
            className={cn(
              "inline-flex cursor-help items-center gap-1 rounded-full border border-sky-200 bg-sky-50 px-1.5 py-0.5 text-[10px] font-medium leading-none text-sky-700",
              className,
            )}
          >
            <Database className="h-2.5 w-2.5" aria-hidden />
            {label ?? t("provenance.source", "Source")}
          </span>
        </TooltipTrigger>
        <TooltipContent className="max-w-[220px] text-xs">
          {tooltip ??
            t(
              "provenance.sourceTooltip",
              "Reported as published by the official source — fetched verbatim, not calculated or estimated by WealthSync.",
            )}
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
